name: CI
on:
  push: { branches: [ main, develop ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      python-versions: '["3.11","3.12"]'
      oses: '["ubuntu-latest"]'
      publish: false

